### ISSUE TITLE
[Android] RoundScreen crash

### ISSUE THREAD

**Issue by TarasYurkiv** [taraspasichnyk/CAH#76]

**Comment by TarasYurkiv** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eleks.cah.android, PID: 2089
    java.lang.IllegalArgumentException: Padding must be non-negative
        at androidx.compose.foundation.layout.PaddingModifier.<init>(Padding.kt:346)
        at androidx.compose.foundation.layout.PaddingModifier.<init>(Unknown Source:0)
        at androidx.compose.foundation.layout.PaddingKt.padding-qDBjuR0(Padding.kt:56)
        at androidx.compose.foundation.layout.PaddingKt.padding-qDBjuR0$default(Padding.kt:50)
        at com.eleks.cah.android.game.round.RoundScreenKt.RoundScreen(RoundScreen.kt:157)
        at com.eleks.cah.android.game.round.RoundScreenKt$RoundScreen$3.invoke(Unknown Source:17)
        at com.eleks.cah.android.game.round.RoundScreenKt$RoundScreen$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2435)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2703)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3326)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3304)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3304)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3269)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:771)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1040)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:245)
        at android.app.ActivityThread.main(ActivityThread.java:8004)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@aa7f700, androidx.compose.ui.platform.MotionDurationScaleImpl@c65b39, StandaloneCoroutine{Cancelling}@b56657e, AndroidUiDispatcher@429cadf]
`


![Image](https://user-images.githubusercontent.com/100289052/222118530-f187ad1e-6118-4c60-86df-1a12f205c162.png)
